### PR TITLE
sorting to / sot, renaming, removing duplicates and small fixes

### PR DESCRIPTION
**Pull request by michal777**
DPAK and IPAK from SMD_Packages and two packages from Discret moved to TO_SOT... and some of them renamed.
Diode from SMD_Packages.pretty moved to diodes.
Some removed duplicates, fixed attributes etc.

KiCad/Diodes_SMD.pretty#11
KiCad/Discret.pretty#7
KiCad/TO_SOT_Packages_SMD.pretty#2
KiCad/TO_SOT_Packages_THT.pretty#2
KiCad/kicad-library#275

### CODE REVIEW

**Comment by ricardocrudo** [comment]
All merged. I did some small changes in some of them.

**Comment by madworm** [comment]
curl https://api.github.com/orgs/KiCad/repos?per_page=2000 2> /dev/null | grep full_name | grep pretty | sed -r  's:.+ "KiCad/(.+)",:\1:' | grep TO_SOT

TO_SOT_Packages_THT.pretty

Where is TO_SOT_Packages_SMD.pretty ???

**Comment by ricardocrudo** [comment]
@madworm https://developer.github.com/v3/#pagination

**Comment by madworm** [comment]
Your social skills are a bit lacking... friend. Useless referrers to documentation suck.

Did You ever check if it works at all?

I copied that curl line almost 100% from the "library-repos-install.sh" script (part of kicad sources, which doesn't work either for this case). I was quite surprised when the DPAK packages were deleted and NOTHING was replacing them...

**Comment by madworm** [comment]
Fine, I plugged in page=1&per_page=100...

github returns a list of 94 repos, TO_SOT_Packages_SMD.pretty is NOT among that.

**Comment by ricardocrudo** [comment]
> Your social skills are a bit lacking... friend. Useless referrers to documentation suck.

@madworm ok, let's see. you are posting in a closed PR about a subject that is not related to this thread, actually it's even related to KiCad libraries, can sound to you it is, but it isn't. You have a issue with github api. Post your issue in proper place and you'll proper answers.

> Did You ever check if it works at all?

Yes, but as I explained before, this does not concern to KiCad libraries.

**Comment by madworm** [comment]
In pull request #30 parts were DELETED. That is a fact. Due to the issue with the installer script (github api change?) NO replacements were installed / found.

Call me stupid, but the problem became apparent by changes to the library HERE.

If that is known, the library folk should've notified the kicad devs, NO?

I've filed a patch with kicad.

EOF

**Pull request merged**
