### PR TITLE
Remove duplicates now found in other libraries

### PR DESCRIPTION
**Pull request by CarlPoirier**
This fixes issue #20. For SMD ICs, as a matter of verification, all the matching ones have been grouped together and can be visualized in [this file](https://drive.google.com/file/d/0B_TuF8sgKAKtTHFWVmcybWRzSmc/view?usp=sharing).

### CODE REVIEW

**Comment by michal777** [comment]
How can I open this modified pretty in kicad? There is no commit on your github account.

**Comment by CarlPoirier** [comment]
I'm not sure to understand what you say.

**Comment by michal777** [comment]
If I add in pcbnew https://github.com/CarlPoirier/SMD_Packages.pretty I see library that is not changed (recent revision is: Adjusted silkscreen width). How can I open modified pretty in kicad when it doesn't exist on your account?

**Comment by CarlPoirier** [comment]
That's weird. I see, visiting this very same link :

This branch is 1 commit ahead of KiCad:master

   -  Pull Request
   <https://github.com/CarlPoirier/SMD_Packages.pretty/pull/new/master>
   -  Compare <https://github.com/CarlPoirier/SMD_Packages.pretty/compare>

Remove duplicates now found in other libraries
<https://github.com/CarlPoirier/SMD_Packages.pretty/commit/fd0d8360b0a2b87c5fd7f253ad62af3ff8880158>
latest commit fd0d8360b0
<https://github.com/CarlPoirier/SMD_Packages.pretty/commit/fd0d8360b0a2b87c5fd7f253ad62af3ff8880158>
[image: CarlPoirier] CarlPoirier <https://github.com/CarlPoirier> authored 6
hours ago

**Comment by michal777** [comment]
Usually when I go to tab "Files changed" and then click "View" I'm redirected to users account (should be https://github.com/CarlPoirier/...). In this case I'm redirected to https://github.com/KiCad/SMD_Packages.pretty/blob/ffb4c04017159ca12b562fd5e60081e8346d55ec/MSOP-10-0.5mm.kicad_mod

**Comment by CarlPoirier** [comment]
That's because I deleted it in my commit, so it is not present in my repo.

**Comment by michal777** [comment]
Thanks for doing this. 
More footprints that are similar or the same:
WSON-8-1EP == DFN-8-1EP_2x2mm_Pitch0.5mm
uMAX-10_Maxim == MSOP-10_3x3mm_Pitch0.5mm
SSOP-17 == TSSOP-16-1EP_4.4x5mm_Pitch0.65mm
TSSOIC-24 == SSOP-24_5.3x8.2mm_Pitch0.65mm
SO-28 == SOIC-28_7.5x17.9mm_Pitch1.27mm
SO-24-E == SOIC-24_7.5x15.4mm_Pitch1.27mm
SO-20-L == SOIC-20_7.5x12.8mm_Pitch1.27mm
SO-16-E == SOIC-16_3.9x9.9mm_Pitch1.27mm

QFN-44-1EP is probably broken - it's described as 7x7 but is 9x9. Probably doesn't exist (I couldn't find it).
All sot-23 can be also removed. The one verision with correct pin numbering is Transistors_SMD.

**Comment by CarlPoirier** [comment]
I confirm these as well.

**Comment by michal777** [comment]
Thanks for cleaning this up.

**Comment by minisystem** [comment]
Github noob here: I've been using this github library and haven't made a local copy. I just noticed that the TSSOP-14 footprint I was using has disappeared from this repository and, sure enough, see that it was removed in the latest commit. Was it removed because it's duplicated elsewhere or is it considered  the same as SSOP-14 and thus considered a duplicate? I'm just confused as I can't seem to find it elsewhere.

**Comment by michal777** [comment]
Most of removed footprints are duplicates of footprints present in Housings_SSOP, Housings_SOIC, Housings_QFP, Housings_DFN_QFN. Please look at SSOP-14 or TSSOP-14 in Housings_SSOP (probably you can use one of them). You can find old verisions in github history: https://github.com/KiCad/SMD_Packages.pretty/tree/ffb4c04017159ca12b562fd5e60081e8346d55ec

**Comment by minisystem** [comment]
Ah. Perfect. Somehow I skipped over all the housings libraries. Thanks!

**Comment by CarlPoirier** [comment]
Indeed, the SMD_Packages library will most probably disappear at some point, as its footprints are being moved to other more specific libraries.

**Pull request merged**
