### PR TITLE
LGA 3x3mm 16l pitch 0.5mm

### PR DESCRIPTION
**Pull request by El3ctr0nic**
LSM303D MEMS footprint

### CODE REVIEW

**Comment by pointhi** [comment]
Please fix KLC:

```
checking module: LGA:LGA-16L_3x3mm_Pitch0.5mm
  Violating Rule 10.1
    Footprint name must match its filename. (.kicad_mod files).
  Violating Rule 10.4
    Value is filled with footprint name and is placed on the fabrication layer.
  Violating Rule 10.5
    Attributes is set to the appropriate value, see tooltip for more information.
  Violating Rule 10.7
    3D Shape ".wrl" files are named the same as their footprint and are placed in a folder named the
    same as the footprint library replacing the ".pretty" with ".3dshapes".
```

also it would be nice to have a better datasheet link without google between: http://e-tools.info/project/download.php?id=18362&usg=AFQjCNH-sbNbe3O_LQOOUDvvz_2Yjx8QFA&cad=rja

**Comment by El3ctr0nic** [comment]
Hi Can You help me how run check script on windows? I Cant hadle it ;( I'm
very poor on python ;/

Ten e-mail został wysłany z komputera wolnego od wirusów chronionego przez
Avast.
www.avast.com <https://www.avast.com/sig-email>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-02-16 16:37 GMT+01:00 Thomas Pointhuber <notifications@github.com>:

**Comment by pointhi** [comment]
Well, I'm removed windows a few years ago from my computers, so I'm not a good help.

But you need to install python first: https://www.python.org/downloads/release/python-351

I would recommend you to ask @SchrodingersGat, he seems to use Windows https://github.com/KiCad/kicad-library-utils/pull/14

**Comment by SchrodingersGat** [comment]
Hey @El3ctr0nic it's very straightforward to run the kicad-library-utils in windows, it just depends on where you have everything installed.

As an example, the following command:

"python c:\kicad\kicad-utils\pcb\check_kicad_mod.py C:\Kicad\share\kicad\modules\pretty\Capacitors_SMD.pretty\C_0201.kicad_mod"

is based on my directory setup but yours may be different.

If you don't have python binary in your PATH, then replace "python" with (for example) "C:\python27\python.exe"

Also you might run into issues with the "print_color.py" file in the "kicad-utils\pcb" directory. Replace it with the file in the schlib directory if this happens.

**Comment by El3ctr0nic** [comment]
Thx works perfekt after print_color replace from schlib ;]

**Comment by pointhi** [comment]
There is a PR with the same footprint contained: https://github.com/KiCad/Housings_DFN_QFN.pretty/pull/20. We have to check out where to place those footprints (probably in a new library)

**Comment by jkriege2** [comment]
Hi!

I asked @SchrodingersGat  to make Repos for BGA, LGA and PGA- housings. Maybe send there?

see: https://github.com/KiCad/kicad-library/pull/970 

JAN

**Comment by SchrodingersGat** [comment]
This has been done.

**Comment by CarlPoirier** [comment]
Yes, please submit your footprint to the relevant repo. No more pull requests are accepted into this one.

https://github.com/KiCad/Housings_LGA.pretty

**Pull request closed without merging**
